name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # --- POIN 3: RUN ASSERTION TEST ---
    - name: Run Logic Testing (Assertion)
      run: |
        # Pastikan class AssertionTest sudah kamu buat di src/test/java/org/ouch/
        mvn exec:java -Dexec.mainClass="org.ouch.AssertionTest" -Dexec.args="-ea"

 
    - name: Run Snyk Security Scan
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: snyk_uat.1fcad39e.eyJlIjoxNzc4MzEyMTYwLCJoIjoic255ay5pbyIsImoiOiJBWjRHaEVlOFptUEE5YXFJaU0xZzRnIiwicyI6ImJRTFMwRWRIVG0yWG1SX3FmelhwMmciLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.Z3jPI-r6ebtxNxoP9zhovIS5yBmdn4kOmpRFjUM0Jypzp7tkMVAIbm4c8uA84H47la-aePdchemLso2leCcVCA
      with:
        args: --severity-threshold=high
